### ISSUE TITLE
Use of FrozenArray<SharedStorageUrlWithMetadata> as an argument type makes no sense

### ISSUE THREAD

**Issue by domenic** [WICG/shared-storage#143]
The spec has two methods which take `FrozenArray<SharedStorageUrlWithMetadata>`.

It's not clear what was intended here. But [per the Web IDL spec](https://webidl.spec.whatwg.org/#js-frozen-array), almost the exact same set of values are accepted compared to accepting the more conventional `sequence<SharedStorageUrlWithMetadata>`.

(The difference is that certain proxies for arrays, which define throwing `getOwnPropertyDescriptor()` traps, would be rejected, because in theory the implementation is supposed to freeze the incoming array.)

We'd like to prohibit the usage of `FrozenArray<T>` as a parameter type in Web IDL, per https://github.com/whatwg/webidl/issues/1399. It would be lovely if you could move to using `sequence<>`s.

**Comment by domenic** [comment]
Ping! This is one of the last things we need to fix to help with https://github.com/whatwg/webidl/issues/1399.

**Comment by xyaoinum** [comment]
This is done in: https://github.com/WICG/shared-storage/pull/162
