### ISSUE TITLE
[spec] Add boolean "shared storage navigation/reporting budget charged" to [=fenced frame config instance=]

### ISSUE THREAD

**Issue by xyaoinum** [WICG/shared-storage#149]
Need to add the boolean **shared storage navigation/reporting budget charged** to [=fenced frame config instance=] in the draft [[Fenced-Frame]] specification, then need to fix the references in the shared storage spec.

**Comment by pythagoraskitty** [comment]
We actually won't need this boolean now, now that we no longer have a reporting entropy budget, if we go back to setting the budget to charge to zero once it has been charged.

We will need to link to the [exfiltration budget metadata (reference)](https://wicg.github.io/fenced-frame/#fencedframetype-exfiltration-budget-metadata) in the [fenced frame spec](https://wicg.github.io/fenced-frame/), however.
