### ISSUE TITLE
[spec] Merge WindowSharedStorage interface with SharedStorage

### ISSUE THREAD

**Issue by xyaoinum** [WICG/shared-storage#154]
Today, the Chrome code and the spec don't match:
- The code has a single `Exposed=(Window, SharedStorageWorklet) interface SharedStorage {...}` interface, and it adds `[Exposed=SharedStorageWorklet]` to prevent individual methods from being exposed from `window.sharedStorage` when inside of a `Window` global specifically.
- The spec puts the common methods into`Exposed=(Window, SharedStorageWorklet) interface SharedStorage`, and puts the Window-only methods into a `[Exposed=(Window)] interface WindowSharedStorage : SharedStorage {}`.

To align with the existing code's functionality, `WindowSharedStorage` should be merged into `SharedStorage` within the spec.

**Comment by domfarolino** [comment]
(Made a very minor edit just FYI, let me know if it looks wrong).
