### ISSUE TITLE
Should the domain of the shared storage script be restricted?

### ISSUE THREAD

**Issue by jkarlin** [WICG/shared-storage#2]
Can A.com load a shared storage worklet from a domain other than A.com? This seems to come down to how much you trust the entities on your page. E.g., if the top frame embeds untrusted script, that untrusted script might create worklets that report bogus aggregate data to poison the site's aggregate data.

Generally, the web does not protect documents from embedding scripts that could do terrible things. Should that same precedent apply here?

**Comment by jkarlin** [comment]
The decision is that the shared storage script's origin must match that of the context that created it. Due to concerns of poisoning and using up the origin's budget. Can revisit later if necessary.

**Comment by alexmturner** [comment]
Would `Access-Control-Allow-Origin` be sufficient here to allow servers to control embedding?

**Comment by jkarlin** [comment]
Thanks for bringing this back up Alex. I do think that header or a similar one to specify that this document is allowed to write to this origin's shared storage or run worklets on its behalf (perhaps separate controls) would provide for significant performance gains (e.g., not having to create an iframe just to write to shared storage).

**Comment by xottabut** [comment]
Hi Alex, Josh, 

I juse tested the next setup:
domain1.com: html page, imitating iframe that requests ad from ad server
```
... creative html here ...
<script src="domain2.com/register_module.js"></script> // could be just inlined js, same result in the end
... creative html here ...
```
domain2.com/register_module.js script that registers module to shared storage worklet 
`...sharedStorage.worklet.addModule("domain2.com/module.js");`

This gives an error that same origin expected. Both registration and module itself have configured CORS headers.

So, looks like it is not allowed to host js module under different domain. Which means that it should be always same origin as ad server, which also means reporting origin will be the same as ad server origin. 

This is not very convinient for clients as ad serving infrastructure might be controlled by different teams/organisations/departments than reporting infrastructure. Devinding by domain would make sense here.

Would you have any suggestions here?

Thanks,
Anatolii

**Comment by alexmturner** [comment]
Hi Anatolii,

We appreciate the feedback. Currently, the shared storage worklet script has to be same-origin as the frame it's embedded in. So, you have to create an iframe to run this script on the different origin. However, as Josh said above, we are considering changing this requirement to avoid the performance issue of creating that iframe.

Best,
Alex

**Comment by jkarlin** [comment]
As noted in the references above, the explainer and spec have been updated with a new capability to create cross-origin worklets directly, without having to first create a x-origin iframe. The worklet script response headers script will need to opt into this with both CORS and a `Shared-Storage-Worklet-Allowed: ?1` header. Be careful with this, as it's not your document that is requesting this worklet to run.
