### ISSUE TITLE
Support event-level reporting for `selectURL()` in the short term

### ISSUE THREAD

**Issue by pythagoraskitty** [WICG/shared-storage#27]
For utility and adoptability, prior to the deprecation of third-party cookies, we will need to support event-level reporting for `sharedStorage.selectURL()` in a manner that is roughly equivalent to what the FLEDGE API has implemented in their [`registerAdBeacon()`](https://github.com/WICG/turtledove/blob/main/Fenced_Frames_Ads_Reporting.md).  

We propose updating the `urls` parameter, which is currently an array of URLs, to an array of dictionaries where the metadata can be omitted, e.g. in the following example:

```js
var opaqueURL = await window.sharedStorage.selectURL(
  "select-url-for-experiment",
  [{url: "blob:https://a.example/123…", report_event: "click", report_url: "https://report.example/1..."},
   {url: "blob:https://b.example/abc…", report_event: "click", report_url: "https://report.example/a..."},
   {url: "blob:https://c.example/789…"}],
  {data: {name: "experimentA"}});
```

We would then use this metadata to hook up to [`window.fence.reportEvent()`](https://github.com/WICG/turtledove/blob/main/Fenced_Frames_Ads_Reporting.md).

In the long term, however, we will not be able to support this type of reporting, as it can be used to leak the index simply by using a distinct `report_url` for each candidate Fenced Frame `url`.  

We welcome feedback on this proposal.

**Comment by xyaoinum** [comment]
Should the worklet also handle dictionaries, or should it just expect the unpacked urls?

It feels more consistent to use the same parameter type. But on the other hand, the reporting data may not be useful inside the worklet.

**Comment by pythagoraskitty** [comment]
My current thinking is to just send the URLs to the worklet (unpacking in
SharedStorageWorkletHost):

https://chromium-review.googlesource.com/c/chromium/src/+/3650846/7/content/browser/shared_storage/shared_storage_worklet_host.cc

As you said, the reporting data isn't useful inside the worklet, so it
seemed strange to plumb it through there.


Camillia
* Smith Barnes*, Ph.D.
***@***.**** ***@***.***>
***@***.**** ***@***.***>
***@***.*** <http://goog_1009150254>*
*www.cammie.tech <http://www.cammie.tech>*
*www.linkedin.com/in/csbphd <http://www.linkedin.com/in/csbphd>*
