### ISSUE TITLE
Question on how much data can be stored in Shared Storage

### ISSUE THREAD

**Issue by gong-doli** [WICG/shared-storage#30]
This would be stored in browser, will there be a restriction on how much data can be stored per partition?

**Comment by etrouton** [comment]
From the public design doc (https://docs.google.com/document/d/1XFbHVFZc8Y5uisNLl3-yiJvY_njCcOMTcHW1AzyUu3I/edit): "We will need storage quotas. A strawman proposal is to have a per-entry size cap of 4 KB—both keys and values will be limited to 1024 char16_t characters apiece—and a per-origin entry cap of 10,000 entries, with a mechanism that prevents additional entries from being committed when an origin’s capacity is full."

Would love to hear feedback on if those limits are reasonable.  Thank you.

**Comment by pythagoraskitty** [comment]
Closing this issue for now, but please re-open (or open a new issue), if you have further questions. Thanks.
