### ISSUE TITLE
Number of bits for the selectURL output gate

### ISSUE THREAD

**Issue by yoavweiss** [WICG/shared-storage#34]
The explainer states that "The chosen URL represents up to log2(num urls) bits of cross-site information", but it's not immediately obvious (to me) why that's the case. Expanding on it (inline in the explainer, or in a separate document) would be appreciated! :)

**Comment by pythagoraskitty** [comment]
I added a couple links to the relevant Wikipedia page.

Also, the [Budgeting](https://github.com/WICG/shared-storage#budgeting) section's explanation may be a bit more fleshed out now.  

Closing for now, but please re-open if you think this has not been sufficiently addressed. Thanks!
