### ISSUE TITLE
Key Lifetime

### ISSUE THREAD

**Issue by RussStringham** [WICG/shared-storage#5]
No mention is made of how long keys are persisted. The set() and append() calls should include an optional parameter that allows the lifetime to be specified. This should default to something like 30 days. If set() is called on an existing key with ignoreIfPresent true, its lifetime should still be updated. You could either always update it to the newly specified expiration or to the latest of its current expiration and its newly specified expiration.

**Comment by jkarlin** [comment]
We had this in our original proposal but removed it before publishing the explainer as we didn't have any solid use cases that required it. What did you have in mind to do with it?

**Comment by pythagoraskitty** [comment]
At the moment, the plan is to periodically clear all keys from origins whose Shared Storage hasn't been accessed at all for a given window yet to be determined (probably something like 30 or 60 days or so), but to persist keys from active origins indefinitely, except for when a user asks for site data to be cleared, or for when the site itself asks for data to be cleared or individual keys to be deleted.  

If you have a use case for auto-expiration for individual keys, however, please do elaborate.

**Comment by pythagoraskitty** [comment]
Keys now auto-expire 30 days after their last update (set or append, even if not modified because of `ignoreIfPresent: true`). So to keep a key from expiring, either overwrite it, append to it, or use set with `ignoreIfPresent: true` to keep the current value but update the expiration time .
