### ISSUE TITLE
A/B experiments on contextual ads or a mix of interest-based and contextual ads

### ISSUE THREAD

**Issue by lbdvt** [WICG/shared-storage#6]
Hi,

My understanding is that FLEDGE and TURTLEDOVE include the support of contextually-targeted ads, that do not need to be rendered in a fenced frame.

A given ad campaign could then be running on contextual signals only, or on both interest-based (TURTLEDOVE/FLEDGE) and contextual data, depending on the result of each ad request. Doing A/B testing on these types of campaigns is an important use case.

How could these use cases be supported by Shared Storage, without having to render contextual ads in a fenced frame?

**Comment by jkarlin** [comment]
We don't currently have a way for shared storage data to get to the embedder, so a fenced frame is the only option at the moment. There is the possibility of providing (heavily noised) data to the embedder, but I worry that the noise would need to be so much that it may not be useful.

**Comment by pythagoraskitty** [comment]
Closing for now. Please re-open or open a new issue if you need further clarification.
