### ISSUE TITLE
Replacing k-anonymity requirement for `selectURL()` with  per-page-load entropy bit budgets 

### ISSUE THREAD

**Issue by pythagoraskitty** [WICG/shared-storage#68]
We are soliciting feedback on the following proposal:

We propose removing the requirement that input URLs for `sharedStorage.selectURL()` be k-anonymous.   

Given that we currently have event-level reporting, we believe a k-anonymity requirement would be of limited benefit and not worth the associated financial, performance, and utility costs.

Instead, each page load would have two entropy-bit budgets: an overall page budget and a per-origin page budget. These budgets are in addition to and separate from the daily budget for navigation.

Each time `selectURL()` is called during that page load, log2(`num_urls`) would be charged to both the overall budget and the per-origin budget for the caller's origin, as long as there is sufficient budget remaining in both.  If either budget has insufficient remaining budget, then the default URL is returned for `selectURL()` and no budget charges are made.

We plan to use 12 bits as the page-load overall budget, and 6 bits as the page-load per-origin budget.

**Comment by SpaceGnome** [comment]
And also, by overall budget, does this mean even if there are multiple different context origins using Shared Storage, all the context origins are contributing to the overall page's budget?

**Comment by pythagoraskitty** [comment]
We will charge you each time that you call `selectURL()`, with the exception that we are going to put into place a best-effort filter to prevent charging you additional times for the same URL during the same page load. (In rare instances you might sill be double-charged if, for example, two calls for the same URL happen simultaneously.)

Yes, the overall budget is contributed to by all origins on the page calling `sharedStorage.selectURL()`.

**Comment by SpaceGnome** [comment]
Makes sense to cache it and perhaps store it in a 1P cookie.

Some other thoughts:

- What happens if there is intentional abuse to hit the budgets (perhaps by a malicious site to easily hit the page-load overall budget) and hence force each context origin to only get the default URL? 
- If this proposal does move forward, could we consider a "soft enforcement" period until there is enough usage to determine if the proposed budgets actually make sense before actual enforcement?

**Comment by SpaceGnome** [comment]
Also, in this proposal, what is the window for the budget? Is it also 24 hours like in the budget for navigations?

**Comment by pythagoraskitty** [comment]
No, this budget is refreshed at the start of each top-level navigation.

**Comment by SpaceGnome** [comment]
Ah, thanks! 

In this case, I think the proposal makes sense.  My only remaining concern is with any malicious sites that intentionally hit the budgets and prevent legitimate users of Shared Storage from getting a non-default URL.
