### ISSUE TITLE
Clarification on Keys/Values

### ISSUE THREAD

**Issue by appascoe** [WICG/shared-storage#8]
@jkarlin We were talking about this spec internally and realized that a couple of us had different interpretations on what would be allowable within the stored keys and values. I'm under the impression that keys and values can be arbitrary strings, and we can run arbitrary code over those strings to produce values for the Aggregate Reporting API.

For example, let's take as a use case that advertisers wish to understand their sales cycle better, and want to measure the average time from first impression served to conversion. Could we do something like (pardon my pseudo-JS/python mix):

```
function getTimestamp() { … }
await window.sharedStorage.worklet.addModule("timetoconversion.js");

// At impression time
window.sharedStorage.set("conversion-timestamps", getTimestamp() + "-", {ignoreIfPresent: true});

// At conversion time
window.sharedStorage.append("time-to-conversion", getTimestamp());
await window.sharedStorage.runOperation("time-to-conversion");
```

With `timetoconversion.js` containing:

```
class SendTimeToConversionReportOperation {
    timestamps = await this.sharedStorage.get("conversion-timestamps");
    t1, t2 = timestamps.split("-");
    time = int(t2) - int(t1);

    this.createAndSendAggregatableReport({
      operation: "sum",  // sum all time delays so we can compute an average later
      key: "time-to-conversion",
      value: time
  }
}
registerOperation("time-to-conversion", SendTimeToConversionReportOperation);
```

Does this make sense? Thanks in advance for any guidance!

**Comment by pythagoraskitty** [comment]
Yes, what you have will work, modulo some easily corrected syntax errors (e.g. your logic inside the `SendTimeToConversionReportOperation` class needs to be wrapped inside a `run()` method), and also with the caveat that your impression-time and conversion-time calls to `set()` will  of course possibly be on different documents, even though you've grouped them together here.

**Comment by pythagoraskitty** [comment]
Closing for now. Please re-open or open a new issue if you need further clarification.
