### ISSUE TITLE
sharedStorage.selectURL doesnt return FencedFrameConfig

### ISSUE THREAD

**Issue by dkdotmetrics** [WICG/shared-storage#82]
Hello, 
trying out sharedStorage.selectURL  as in example:
https://github.com/WICG/shared-storage#simple-example-consistent-ab-experiments-across-sites

using resolveToConfig: true, doesn't return FencedFrameConfig but just resolves as opaque URN.

Is there anything else that needs to be enabled to test this feature?

**Comment by pythagoraskitty** [comment]
Yes you need to have the "FencedFramesAPIChanges" feature enabled.  It looks like this feature is not listed in chrome://flags, however, so you'd need to enable it from the command line.  Perhaps someone from the Fenced Frames team could comment.

**Comment by blu25** [comment]
+1 to what @pythagoraskitty said. If you specify that you want to resolve to a config, but the `FencedFramesAPIChanges` is not enabled, it quietly falls back to resolving to a URN.

**Comment by dkdotmetrics** [comment]
thank you! works fine when running using command line.
in ubuntu:
google-chrome-stable --enable-features=FencedFramesAPIChanges
