### ISSUE TITLE
Interaction between sharedStorage selectURL and runAdAuction

### ISSUE THREAD

**Issue by stguav** [WICG/shared-storage#84]
The [Protected Audience API](https://github.com/WICG/turtledove/blob/main/FLEDGE.md) (aka Fledge) `runAdAuction` call returns null or is opaque. Similarly the selectURL call response is opaque, with both intended to be rendered in a fenced frame. Unfortunately, using both APIs together seems impractical. 

Consider the frequency capping use-case. Note first that the ATPs involved need to decide ahead of time that they want to use the APIs, without knowing whether the user has any relevant interest groups or any relevant frequency capping data in sharedStorage. The outputs of the two calls correspond to ads with different bids. Since the outputs are opaque, it is not possible in general to know how the bids compare, or which opaque output should be preferred. It may be possible to know or predict in some cases; however this seems like a significant gap.

Should it be possible to feed the output of one API into the other in a way that would make selecting based on the maximum bid possible?

**Comment by jkarlin** [comment]
Thanks for the report! 

> Should it be possible to feed the output of one API into the other in a way that would make selecting based on the maximum bid possible?

Yes, I believe it should. This seems like an important set of use cases to support. Note that the explainer now states that it is possible to call `selectURL` from the root fenced frame, regardless of the API that generated the FF's config.
